### ISSUE TITLE
Error whie performing -->  yarn migrate:demo

### ISSUE THREAD

**Issue by devrajsinghrawat** [energywebfoundation/origin-integration-example#14]
```
➜  origin-integration-example git:(master) ✗ yarn migrate:demo
yarn run v1.22.10
$ yarn typeorm:migrate && origin-migrations -e .env -c config/demo-config.json -s config/seed.sql
$ typeorm migration:run --config node_modules/@energyweb/exchange/dist/js/ormconfig.js && typeorm migration:run --config node_modules/@energyweb/origin-backend/dist/js/ormconfig.js
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'migrations_exchange'
query: SELECT * FROM "migrations_exchange" "migrations_exchange"  ORDER BY "id" DESC
No migrations are pending
query: SELECT * FROM "information_schema"."tables" WHERE "table_schema" = current_schema() AND "table_name" = 'migrations_backend'
query: SELECT * FROM "migrations_backend" "migrations_backend"  ORDER BY "id" DESC
No migrations are pending
info: Connected to localhost:5432 - database origin
info: Is first migration: true
info: Deploying contracts to http://localhost:8545...
Registry created at 0x74f482C517e773B7D00ae2084399965D9e0C5274
Issuer v0.1 created at 0x2C9CcC2AC3eAe30E45605Ed2d300d73B3C535D80
info: Saving configuration...
(node:37312) UnhandledPromiseRejectionWarning: error: column "contractsLookup" of relation "configuration" does not exist
    at Parser.parseErrorMessage (/Users/dev-d/1-WorkspaceSlockit/Identity/ew/origin-integration-example/node_modules/pg-protocol/dist/parser.js:278:15)
    at Parser.handlePacket (/Users/dev-d/1-WorkspaceSlockit/Identity/ew/origin-integration-example/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/dev-d/1-WorkspaceSlockit/Identity/ew/origin-integration-example/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/dev-d/1-WorkspaceSlockit/Identity/ew/origin-integration-example/node_modules/pg-protocol/dist/index.js:8:42)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:37312) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:37312) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by devrajsinghrawat** [comment]
this was resolved when I had deleted the postgres container and staretd a new one .. Seems issue with Docker instance
